// Curated subset of lucide-react icons available for categories. Named imports
// (not `import * as Icons`) so bundlers can tree-shake every icon not listed here.
import type { LucideIcon } from "lucide-react";
import {
  Ban,
  GraduationCap,
  Dumbbell,
  Users,
  DollarSign,
  HeartPulse,
  Briefcase,
  Utensils,
  Home,
  Trees,
  Square,
  Book,
  BookOpen,
  PenTool,
  Code,
  Palette,
  Music,
  Camera,
  Film,
  Gamepad2,
  Bike,
  Footprints,
  Waves,
  Sun,
  Moon,
  Cloud,
  Coffee,
  Wine,
  Pill,
  Stethoscope,
  Bed,
  Baby,
  Dog,
  Cat,
  Car,
  Plane,
  Bus,
  ShoppingCart,
  Wallet,
  PiggyBank,
  TrendingUp,
  Wrench,
  Hammer,
  Leaf,
  Flower2,
  Mountain,
  Tent,
  Phone,
  Mail,
  Calendar,
  Clock,
  Target,
  Star,
  Heart,
  Smile,
  Brain,
  Globe,
  Languages,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  ban: Ban,
  "graduation-cap": GraduationCap,
  dumbbell: Dumbbell,
  users: Users,
  "dollar-sign": DollarSign,
  "heart-pulse": HeartPulse,
  briefcase: Briefcase,
  utensils: Utensils,
  home: Home,
  trees: Trees,
  square: Square,
  book: Book,
  "book-open": BookOpen,
  "pen-tool": PenTool,
  code: Code,
  palette: Palette,
  music: Music,
  camera: Camera,
  film: Film,
  "gamepad-2": Gamepad2,
  bike: Bike,
  footprints: Footprints,
  waves: Waves,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  coffee: Coffee,
  wine: Wine,
  pill: Pill,
  stethoscope: Stethoscope,
  bed: Bed,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  car: Car,
  plane: Plane,
  bus: Bus,
  "shopping-cart": ShoppingCart,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  wrench: Wrench,
  hammer: Hammer,
  leaf: Leaf,
  "flower-2": Flower2,
  mountain: Mountain,
  tent: Tent,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  clock: Clock,
  target: Target,
  star: Star,
  heart: Heart,
  smile: Smile,
  brain: Brain,
  globe: Globe,
  languages: Languages,
};

export const CURATED_ICON_NAMES = Object.keys(ICON_REGISTRY);

export const DEFAULT_ICON_NAME = "square";
